version: '3.8'

services:
  sistema-npj-db-1:
    image: mysql:8.0
    container_name: sistema-npj-db-1
    environment:
      MYSQL_ROOT_PASSWORD: 12345678@
      MYSQL_DATABASE: npjdatabase
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: npj-backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: sistema-npj-db-1
      DB_USER: root
      DB_PASSWORD: 12345678@
      DB_NAME: npjdatabase
    depends_on:
      sistema-npj-db-1:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: npj-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local